/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabriel Kresin e Iago Tambosi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrarReceita = new javax.swing.JButton();
        btnConferirSaldo = new javax.swing.JButton();
        btnVisualizarDespesas = new javax.swing.JButton();
        btnVisualizarEntradas = new javax.swing.JButton();
        btnVisualizarLancamentos = new javax.swing.JButton();
        btnCadastrarDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCadastrarReceita.setText("Cadastrar Receita");
        btnCadastrarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarReceitaActionPerformed(evt);
            }
        });

        btnConferirSaldo.setText("Conferir saldo:");
        btnConferirSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferirSaldoActionPerformed(evt);
            }
        });

        btnVisualizarDespesas.setText("Visualizar Despesas");
        btnVisualizarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarDespesasActionPerformed(evt);
            }
        });

        btnVisualizarEntradas.setText("Visualizar Entradas");
        btnVisualizarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarEntradasActionPerformed(evt);
            }
        });

        btnVisualizarLancamentos.setText("Visualizar Lançamentos");
        btnVisualizarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarLancamentosActionPerformed(evt);
            }
        });

        btnCadastrarDespesa.setText("Cadastrar Despesa");
        btnCadastrarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarDespesas)
                    .addComponent(btnVisualizarEntradas)
                    .addComponent(btnVisualizarLancamentos)
                    .addComponent(btnCadastrarReceita)
                    .addComponent(btnCadastrarDespesa)
                    .addComponent(btnConferirSaldo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConferirSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarLancamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConferirSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferirSaldoActionPerformed
        MostrarSaldo telaSaldo = new MostrarSaldo(this, true);
        telaSaldo.setVisible(true);
    }//GEN-LAST:event_btnConferirSaldoActionPerformed

    private void btnCadastrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarReceitaActionPerformed
       CadastroReceita cadastroReceita = new CadastroReceita(this, true);
       cadastroReceita.setVisible(true);
    }//GEN-LAST:event_btnCadastrarReceitaActionPerformed

    private void btnVisualizarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarLancamentosActionPerformed
        VisualizarLancamentos visualizarLancamentos = new VisualizarLancamentos(this, true);
        visualizarLancamentos.setVisible(true);
    }//GEN-LAST:event_btnVisualizarLancamentosActionPerformed

    private void btnCadastrarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDespesaActionPerformed
        CadastroDespesa cadastroDespesa = new CadastroDespesa(this, true);
        cadastroDespesa.setVisible(true);
    }//GEN-LAST:event_btnCadastrarDespesaActionPerformed

    private void btnVisualizarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarEntradasActionPerformed
        VisualizarReceitas visualizarReceitas = new VisualizarReceitas(this, true);
        visualizarReceitas.setVisible(true);
    }//GEN-LAST:event_btnVisualizarEntradasActionPerformed

    private void btnVisualizarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarDespesasActionPerformed
        VisualizarDespesas visualizarDespesas = new VisualizarDespesas(this, true);
        visualizarDespesas.setVisible(true);
    }//GEN-LAST:event_btnVisualizarDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDespesa;
    private javax.swing.JButton btnCadastrarReceita;
    private javax.swing.JButton btnConferirSaldo;
    private javax.swing.JButton btnVisualizarDespesas;
    private javax.swing.JButton btnVisualizarEntradas;
    private javax.swing.JButton btnVisualizarLancamentos;
    // End of variables declaration//GEN-END:variables
}
